database:
  driver: postgres
  dbname: instatasks_production
#  username: dbuser
#  password:
  host: postgres
  port: 5432
  # connection pool
  max_open_conns: 100
  max_idle_conns: 10

redis:
  addr: redis:6379

  ### CONNECTION POOL OPTIONS

  ## Minimum number of idle connections which is useful when establishing
  ## new connection is slow.
  ## min_idle_conns: 32

  ## Connection age at which client retires (closes) the connection.
  ## Default is to not close aged connection
  ## max_conn_age: 10

  ## Maximum number of socket connections.
  ## Default is 10 connections per every CPU as reported by runtime.NumCPU.
  # pool_size: 100

server:
  body_crypt: false
  rsa_key_size: 2048 #bytes
  cache:
    #expiration hours
    new_user_expiration: 24 
    user_expiration: 48
    new_task_expiration: 48
    task_expiration: 48
  # By default server will serve an unbounded number of requests. 
  # Limiting the number of simultaneous connections can sometimes
  # greatly speed things up under load.
  connection_limit: 0 # if 0 - No Limit
