database:
  driver: postgres
  dbname: instatasks_production
  username: dbuser
  host: postgres
  port: 5432
  # connection pool
  max_open_conns: 100
  max_idle_conns: 50

redis:
  addr: redis:6379
  # connection pool
  min_idle_conns: 50
  max_conn_age:   1
  pool_size: 100

server:
  rsa_key_size: 2048 #bytes
  cache:
    #expiration hours
    new_user_expiration: 12 
    user_expiration: 2
  