version: '3.4'

services:

  #############################
  ## PostgreSQL
  postgres:
    container_name: instatasksdb
    image: postgres:alpine
    restart: always
    hostname: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
#      - docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:z
    env_file: 
      - docker.env
    ports:
      - 5432
    networks:
      - postgresnet
    deploy:
      mode: replicated
      replicas: 3
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: 10m
  ##################################
  ## Redis
  redis:
    hostname: redis
    image: redis:alpine
    restart: on-failure
    env_file: 
      - docker.env
    volumes:
      # - ./redis_storage/data:/data
      - ./redis_storage/config:/usr/local/etc/redis:ro
    ports:
      - 6379
    networks:
      - redisnet
    deploy:
      mode: replicated
      replicas: 2
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: 10m
    command: >
      sh -c "env redis-server
      --loglevel $$REDIS_LOGLEVEL
      --databases $$REDIS_DATABASES
      --appendonly $$REDIS_APPENDONLY
      --maxmemory $$REDIS_MAXMEM
      --maxmemory-policy $$REDIS_POLICY
      --requirepass $$REDIS_PASSWORD"

  ##############################
  ## WEB
  web:
    container_name: instatasks
    image: djekxa/instatasks:v1
    hostname: instatasks
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - instatasksnet
      - postgresnet
      - redisnet
    volumes:
      - .:/go/src/instatasks:ro
    ports:
      - 80:80
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - postgres
      - redis
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: 10m
    links:
      - postgres
      - redis
###############################
## NETWORKS
networks:
  instatasksnet:
    driver: bridge
#    attachable: true
  postgresnet:
    driver: overlay
#    attachable: true
  redisnet:
    driver: overlay
#    attachable: true
##############################
## VOLUMES
volumes:
  pgdata:
    driver: local-persist
    driver_opts:
      mountpoint: /home/deploy/mnt/postgresql/pgdata
  docker-entrypoint-initdb.d:
    driver: local-persist
    driver_opts:
      mountpoint: /home/deploy/mnt/postgresql/docker-entrypoint-initdb.d